name: ci

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
  - cron: "0 0 * * 0"

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        sdk: [ 2.18.0, dev ]
    steps:
    - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab
    - uses: dart-lang/setup-dart@d6a63dab3335f427404425de0fbfed4686d93c4f
      with:
        sdk: ${{ matrix.sdk }}
    - run: dart pub get
    - run: dart format --output=none --set-exit-if-changed .
    - run: dart analyze --fatal-infos
    - run: dart test
